# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-22 10:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set([('owner', 'blog')]),
        ),
    ]
